import type { BrowserContext, Cookie } from 'playwright-core';
import fs from 'fs/promises';
import path from 'path';

/** Netscape cookie file parser/exporter */
export async function exportCookiesNetscape(context: BrowserContext, outPath: string): Promise<number> {
  const cookies = await context.cookies();
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by BZ Browser',
  ];
  for (const c of cookies) {
    const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
    const flag = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiry = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
    lines.push([domain, flag, c.path, secure, expiry, c.name, c.value].join('\t'));
  }
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, lines.join('\n'));
  return cookies.length;
}

export async function importCookiesNetscape(context: BrowserContext, filePath: string): Promise<number> {
  try {
    const raw = await fs.readFile(filePath, 'utf-8');
    const cookies: Cookie[] = [];
    for (const line of raw.split('\n')) {
      if (!line.trim() || line.startsWith('#')) continue;
      const parts = line.split('\t');
      if (parts.length < 7) continue;
      const [domain, , cookiePath, secure, expiry, name, ...valueParts] = parts;
      cookies.push({
        name,
        value: valueParts.join('\t'),
        domain, // keep leading dot for subdomain match correctness (BUG 3 fixed)
        path: cookiePath,
        secure: secure === 'TRUE',
        expires: parseInt(expiry, 10) || -1,
        httpOnly: false,
        sameSite: 'Lax',
      });
    }
    if (cookies.length > 0) {
      await context.addCookies(cookies);
      return cookies.length;
    }
  } catch (err) {
    console.error('[CookieManager] failed to import Netscape cookies:', err);
  }
  return 0;
}

export async function exportCookiesJson(context: BrowserContext, outPath: string): Promise<number> {
  const cookies = await context.cookies();
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, JSON.stringify(cookies, null, 2));
  return cookies.length;
}

export async function importCookiesJson(context: BrowserContext, filePath: string): Promise<number> {
  try {
    const raw = await fs.readFile(filePath, 'utf-8');
    if (!raw.trim()) return 0;
    const cookies = JSON.parse(raw) as Cookie[];
    if (Array.isArray(cookies) && cookies.length > 0) {
      await context.addCookies(cookies);
      return cookies.length;
    }
  } catch (err) {
    console.error('[CookieManager] failed to import JSON cookies:', err);
  }
  return 0;
}
